### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by julien9999** [sornani/TitaniumJSExtractor#1]
Hey, could you please tell me how to use this ?
thanks

**Comment by sornani** [comment]
0. Decompile APK file and extract Java source code: http://www.javadecompilers.com/apk
1. JavaScript code is stored in a file called AssetCryptImpl.java. Optionally, take a look at this: https://github.com/appcelerator/titanium_mobile/blob/1607237763f9e490e41d98b8d711ac49eeb01043/android/dev/TitaniumTest/src/com/titanium/test/AssetCryptImpl.java
2. Open Extractor.java file. Replace the marked lines with the corresponding Java code extracted from AssetCryptImpl.java file.
3. Compile: javac Extractor.java
4. Run: java Extractor

**Comment by julien9999** [comment]
great, thanks.
Same tool for iOS ?

**Comment by sornani** [comment]
I've never tried it on iOS. I'll let you know when I have the answer.
